# Generated by Django 4.1.9 on 2023-06-03 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poc",
            name="linkedin_url",
        ),
    ]
