# Generated by Django 4.1.9 on 2023-06-04 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_poc_linkedin_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poc",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="pocs", to="core.company"
            ),
        ),
    ]
