# Generated by Django 4.1.9 on 2023-06-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_poc_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorship",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
