# Constants
event_domain_keywords = {
    "hackathon": [
        "technology",
        "software",
        "hardware",
        "computer",
        "programming",
        "coding",
        "hackathon",
        "hackathons",
        "AR",
        "VR",
        "AI",
        "ML",
        "machine learning",
        "artificial intelligence",
        "virtual reality",
        "augmented reality",
        "robotics",
        "robotic",
        "cloud",
        "computing",
        "cloud computing",
        "blockchain",
        "crypto",
        "cryptocurrency",
        "cybersecurity",
        "cyber security",
        "cyber",
        "security",
        "information security",
        "information",
        "information technology",
        "information tech",
        "information technologies",
        "backend",
        "front end",
        "frontend",
        "full stack",
    ],
}
