# Generated by Django 4.1.9 on 2023-06-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_token",
            field=models.TextField(blank=True, null=True, verbose_name="Access Token"),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="Linkedin ID"),
        ),
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.TextField(blank=True, null=True, verbose_name="Refresh Token"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, max_length=255, verbose_name="Email of User"),
        ),
    ]
