# Generated by Django 4.1.9 on 2023-06-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_access_token_user_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linkedin_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="Linkedin ID"),
        ),
    ]
